"""Generate the deterministic mock-generation WAV fixture.

Produces a 2-second, 48kHz, stereo, 16-bit PCM audio clip containing an
audible three-note arpeggio (not silence). Uses only the Python standard
library so the fixture is reproducible anywhere:

    uv run python scripts/development/make_mock_fixture.py

The output is committed at tests/fixtures/mock_generation.wav and is what
MockGenerationProvider returns. It is a test fixture — never presented as
real AI-generated music.
"""

from __future__ import annotations

import math
import struct
import wave
from collections.abc import Iterator
from pathlib import Path

SAMPLE_RATE = 48_000
DURATION_SECONDS = 2.0
CHANNELS = 2
SAMPLE_WIDTH_BYTES = 2  # 16-bit PCM
AMPLITUDE = 0.4
NOTES_HZ = (440.0, 554.37, 659.25)  # A4, C#5, E5 — an A-major arpeggio

#: A bass note under each chord tone, two octaves down.
#:
#: Without it every partial lands between 400 Hz and 2 kHz — one
#: analysis band holding 98% of the energy, which is the shape of a
#: single tone rather than of a mix, and Phase 29 says so. A record has
#: a bottom end; so should the file that stands in for one.
BASS_DIVISOR = 4.0
BASS_WEIGHT = 0.85

#: Harmonic series per note, as (multiple, relative amplitude).
#:
#: Pure sines are not merely dull, they are *technically* degenerate: a
#: 440 Hz tone puts 85% of its energy below 600 Hz with a spectral slope
#: steeper than -12 dB/octave, which is the shape of a collapsed
#: generation. Phase 29 measures exactly that, and it was right to say
#: so — a provider that emitted this would have failed.
#:
#: This double is meant to stand in for model output through a pipeline
#: that now checks whether output is technically plausible, so the
#: fixture carries a harmonic series. Nothing here claims to be music;
#: it claims to be audio with a spectrum a real instrument could have.
HARMONICS = ((1, 1.0), (2, 0.5), (3, 0.28), (4, 0.16), (5, 0.09), (7, 0.05), (9, 0.03))

#: A little broadband noise, and a little of it different per channel.
#:
#: Two degeneracies to remove, both of which made this file behave
#: unlike any real recording. A harmonic stack has *nothing* above its
#: top partial, so a high-shelf lift has nothing to lift and the
#: finishing engine's own acceptance gate correctly refuses its work.
#: And identical channels are perfectly correlated, so every stereo
#: measurement reads as a degenerate case rather than a narrow mix.
#:
#: The noise is generated by a fixed linear congruential sequence rather
#: than `random`, so the fixture is byte-identical on every machine and
#: every Python version — the whole point of a committed fixture.
NOISE_AMPLITUDE = 0.02
_LCG_MODULUS = 2**31
_LCG_MULTIPLIER = 1103515245
_LCG_INCREMENT = 12345

OUTPUT = Path(__file__).resolve().parents[2] / "tests" / "fixtures" / "mock_generation.wav"

_HARMONIC_NORM = sum(weight for _, weight in HARMONICS) + BASS_WEIGHT


def _noise_stream() -> Iterator[float]:
    """A deterministic sequence in [-1, 1). Reproducible everywhere."""
    state = 987_654_321
    while True:
        state = (_LCG_MULTIPLIER * state + _LCG_INCREMENT) % _LCG_MODULUS
        yield (state / (_LCG_MODULUS / 2)) - 1.0


def synthesize() -> bytes:
    total_frames = int(SAMPLE_RATE * DURATION_SECONDS)
    frames_per_note = total_frames // len(NOTES_HZ)
    noise = _noise_stream()
    samples = bytearray()
    for i in range(total_frames):
        note = NOTES_HZ[min(i // frames_per_note, len(NOTES_HZ) - 1)]
        # Short attack/release envelope per note to avoid clicks.
        pos = i % frames_per_note
        env = min(1.0, pos / 480, max(0.0, (frames_per_note - pos) / 480))
        # Summed harmonics, normalised so the peak stays at AMPLITUDE
        # whatever the series length.
        timbre = sum(
            weight * math.sin(2 * math.pi * note * multiple * i / SAMPLE_RATE)
            for multiple, weight in HARMONICS
        )
        timbre += BASS_WEIGHT * math.sin(2 * math.pi * (note / BASS_DIVISOR) * i / SAMPLE_RATE)
        tone = AMPLITUDE * env * timbre / _HARMONIC_NORM
        for _ in range(CHANNELS):
            # Independent noise per channel: identical channels give a
            # correlation of exactly 1.0, which is a degenerate reading
            # rather than a narrow mix.
            value = tone + NOISE_AMPLITUDE * env * next(noise)
            pcm = max(-32767, min(32767, int(value * 32767)))
            samples += struct.pack("<h", pcm)
    return bytes(samples)


def main() -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with wave.open(str(OUTPUT), "wb") as wav:
        wav.setnchannels(CHANNELS)
        wav.setsampwidth(SAMPLE_WIDTH_BYTES)
        wav.setframerate(SAMPLE_RATE)
        wav.writeframes(synthesize())
    print(f"wrote {OUTPUT} ({OUTPUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
