"""Shared schemas and domain enums for LUBER MUSIC AI."""

from luber_schemas.enums import (
    AssetType,
    ErrorCode,
    GenerationStatus,
    VocalGender,
)
from luber_schemas.songcraft import (
    BPM_MAX,
    BPM_MIN,
    DURATION_MAX,
    DURATION_MIN,
    DURATION_PRESETS,
    LONG_FORM_THRESHOLD_SECONDS,
    SECTION_TAG_PALETTE,
    UNEXPOSED_ENGINE_PARAMETERS,
    VALID_KEY_SCALES,
    VALID_TIME_SIGNATURE_VALUES,
    Advisory,
    AdvisoryLevel,
    ParsedStructure,
    Section,
    SectionKind,
    analyze_density,
    audit_korean_lyrics,
    estimate_syllables,
    korean_ratio,
    parse_structure,
    preflight,
    validate_structure,
)

__all__ = [
    "BPM_MAX",
    "BPM_MIN",
    "DURATION_MAX",
    "DURATION_MIN",
    "DURATION_PRESETS",
    "LONG_FORM_THRESHOLD_SECONDS",
    "SECTION_TAG_PALETTE",
    "UNEXPOSED_ENGINE_PARAMETERS",
    "VALID_KEY_SCALES",
    "VALID_TIME_SIGNATURE_VALUES",
    "Advisory",
    "AdvisoryLevel",
    "AssetType",
    "ErrorCode",
    "GenerationStatus",
    "ParsedStructure",
    "Section",
    "SectionKind",
    "VocalGender",
    "analyze_density",
    "audit_korean_lyrics",
    "estimate_syllables",
    "korean_ratio",
    "parse_structure",
    "preflight",
    "validate_structure",
]
